const API_URL='https://script.google.com/macros/s/AKfycbwKWbxAmhxrZiA6o8xKQjEzyiR7GRZuimvh2KxcVFbf_CGfGqaQOegOOMQR-c9AYNqk/exec';
let user=null,cur=null,str=null,userLoc='-',profilePhotoData=null;
const $=s=>document.querySelector(s);
const fixFoto=u=>{if(!u)return'icon-192.png';const id=(u.match(/[-\w]{25,}/)||[])[0];return id?`https://lh3.googleusercontent.com/d/${id}`:u};
const fW=d=>new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(d);
const fD=d=>new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(d);

const apiCache={get:k=>{const v=sessionStorage.getItem(k);if(!v)return null;const o=JSON.parse(v);return Date.now()-o.t<5e3?o.d:null},set:(k,d)=>sessionStorage.setItem(k,JSON.stringify({t:Date.now(),d}))};
async function api(p){const k=p.action+"_"+(p.username||"");if("getRekap"===p.action&&apiCache.get(k))return apiCache.get(k);const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain"},body:JSON.stringify(p),keepalive:!0}),j=await r.json();if(j.error)throw new Error(j.error);return"getRekap"===p.action&&apiCache.set(k,j),j}

// KOMPRES CEPAT
async function kompres(file,max=720,q=0.72){const bmp=await createImageBitmap(file);const s=Math.min(max/bmp.width,max/bmp.height,1);const c=document.createElement('canvas');c.width=bmp.width*s;c.height=bmp.height*s;c.getContext('2d',{willReadFrequently:true}).drawImage(bmp,0,0,c.width,c.height);return c.toDataURL('image/jpeg',q)}

function show(i){document.querySelectorAll('#app>div').forEach(v=>v.classList.add('hidden'));$('#'+i).classList.remove('hidden')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').classList.add('hidden');try{user=await api({action:'login',username:$('#username').value.trim(),password:$('#password').value});localStorage.absensi_user=JSON.stringify(user);init()}catch(err){$('#loginError').textContent=err.message;$('#loginError').classList.remove('hidden')}};
$('#togglePass').onclick=()=>{const p=$('#password');p.type=p.type==='password'?'text':'password';$('#togglePass').textContent=p.type==='password'?'👁':'🙈'};
function init(){show('homeView');$('#namaHome').textContent=user.nama;$('#avatarHome').src=fixFoto(user.foto);tick();setInterval(tick,1000)}
function tick(){const n=new Date();$('#jamHomeBig').textContent=fW(n).replace(/:/g,'.');$('#tanggalHomeBig').textContent=fD(n);$('#hariHome').textContent=fD(n);$('#jam').textContent=fW(n);$('#tanggal').textContent=fD(n)}
$('#logoutBtn').onclick=()=>{localStorage.removeItem('absensi_user');location.reload()};
$('#cardAbsensi').onclick=()=>{show('absensiView');loadT()};$('#cardRekap').onclick=()=>{show('rekapView');loadR()};$('#cardProfil').onclick=()=>openProfile();document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('homeView'));
async function loadT(){try{const a=await api({action:'getAbsensi',username:user.username});$('#timeIn').textContent=a.masuk||'-';$('#timeOut').textContent=a.pulang||'-';const bI=$('#btnIn'),bO=$('#btnOut');bI.disabled=bO.disabled=false;bI.classList.remove('opacity-40');bO.classList.remove('opacity-40');bI.textContent='Masuk';bO.textContent='Pulang';if(a.masuk&&!a.pulang){bI.disabled=true;bI.classList.add('opacity-40')}else if(a.masuk&&a.pulang){bI.disabled=bO.disabled=true;bI.classList.add('opacity-40');bO.classList.add('opacity-40')}else{bO.disabled=true;bO.classList.add('opacity-40')}}catch(e){}}
$('#btnIn').onclick=()=>openC('in');$('#btnOut').onclick=()=>openC('out');
async function openC(t){cur=t;$('#camModal').classList.replace('hidden','flex');str=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:1280}});$('#video').srcObject=str;$('#camWatermark').classList.remove('hidden');$('#wmNama').textContent=user.nama;if(navigator.geolocation){navigator.geolocation.getCurrentPosition(p=>{userLoc=`${p.coords.latitude.toFixed(5)},${p.coords.longitude.toFixed(5)}`;$('#wmLokasi').textContent=userLoc},()=>{$('#wmLokasi').textContent='-'})}clearInterval(window.wmTimer);window.wmTimer=setInterval(()=>{$('#wmWaktu').textContent=fW(new Date()).replace(/:/g,'.')+' WIB'},500)}
function closeC(){$('#camModal').classList.replace('flex','hidden');$('#camWatermark').classList.add('hidden');clearInterval(window.wmTimer);if(str)str.getTracks().forEach(t=>t.stop())}
$('#cancelCam').onclick=closeC;
$('#snapBtn').onclick=async()=>{const v=$('#video'),c=$('#canvas'),x=c.getContext('2d');const s=Math.min(720/v.videoWidth,1);c.width=v.videoWidth*s;c.height=v.videoHeight*s;x.drawImage(v,0,0,c.width,c.height);const n=new Date();x.shadowColor='rgba(0,0,0,0.8)';x.shadowBlur=4;x.fillStyle='#fff';x.font=`${22*s}px sans-serif`;x.fillText(user.nama,20*s,c.height-70*s);x.font=`${18*s}px sans-serif`;x.fillText(userLoc,20*s,c.height-45*s);x.fillText(`${fD(n)} ${fW(n)}`,20*s,c.height-20*s);closeC();$('#statusMsg').textContent='Mengirim...';try{const[lat,lng]=userLoc.split(',');const photo=c.toDataURL('image/jpeg',0.72);await api({action:'absen',username:user.username,type:cur,photo,lat,lng});$('#statusMsg').textContent='Berhasil!';apiCache.set('getAbsensi_'+user.username,null);loadT()}catch(e){$('#statusMsg').textContent=e.message}};
async function loadR(){const r=await api({action:'getRekap',username:user.username});const b=$('#rekapBody');b.innerHTML='';let h=0;for(let i=1;i<=31;i++){const t=r[i]||{};if(t.in)h++;b.innerHTML+=`<tr class="border-t border-white/5"><td class="py-1">${String(i).padStart(2,'0')}</td><td class="text-center font-mono">${t.in||'-'}</td><td class="text-center font-mono">${t.out||'-'}</td></tr>`}$('#totalKerja').textContent=`Total: ${h} hari`;$('#rekapTitle').textContent='Rekap '+new Date().toLocaleString('id-ID',{month:'long',year:'numeric'})}
$('#refreshBtn').onclick=()=>{apiCache.set('getRekap_'+user.username,null);loadR()};
async function openProfile(){show('profileView');$('#profileMsg').textContent='';try{const p=await api({action:'getProfile',username:user.username});$('#profileAvatar').src=fixFoto(p.foto);$('#pfNama').value=p.nama;$('#pfUsername').value=p.username;$('#pfNoHp').value=p.noHp||'';$('#pfAlamat').value=p.alamat||'';$('#pfNoRek').value=p.noRek||'';$('#pfTtl').value=p.ttl||'';profilePhotoData=null}catch(e){$('#profileMsg').textContent=e.message}}
$('#changePhotoBtn').onclick=()=>$('#photoInput').click();
$('#photoInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;profilePhotoData=await kompres(f,600,0.75);$('#profileAvatar').src=profilePhotoData};
document.querySelectorAll('[data-toggle]').forEach(b=>{b.onclick=()=>{const id=b.getAttribute('data-toggle');const i=$('#'+id);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'👁':'🙈'}});
$('#profileForm').onsubmit=async e=>{e.preventDefault();const p1=$('#pfPass1').value,p2=$('#pfPass2').value;if(p1&&p1!==p2){$('#profileMsg').textContent='Password tidak sama';return}$('#profileMsg').textContent='Menyimpan...';const data={noHp:$('#pfNoHp').value,alamat:$('#pfAlamat').value,noRek:$('#pfNoRek').value,ttl:$('#pfTtl').value};if(p1)data.password=p1;if(profilePhotoData)data.fotoProfil=profilePhotoData;try{const res=await api({action:'updateProfile',username:user.username,data});if(res.foto){user.foto=fixFoto(res.foto);localStorage.absensi_user=JSON.stringify(user);$('#avatarHome').src=user.foto}$('#profileMsg').textContent='Berhasil disimpan';$('#pfPass1').value='';$('#pfPass2').value='';setTimeout(()=>show('homeView'),800)}catch(err){$('#profileMsg').textContent=err.message}};
window.onload=()=>{const s=localStorage.absensi_user;if(s){try{user=JSON.parse(s);init()}catch{localStorage.removeItem('absensi_user');show('loginView')}}else show('loginView')};
